export const GET_ERROR  = "GET_ERROR"
export const SET_CURRENT_USER  = "SET_CURRENT_USER"
export const PROFILE_LOADING  = "PROFILE_LOADING"
export const GET_PROFILE  = "GET_PROFILE"
export const GET_PROFILES  = "GET_PROFILES"
export const CLEAR_PROFILE  = "CLEAR_PROFILE"

